language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
os:
  - linux
  - osx
# command to install dependencies
install:
  - python setup.py install
# command to run tests
script:
  - python setup.py test
